# Generated by Django 5.1.3 on 2024-11-29 10:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('specific_motion', models.CharField(max_length=255)),
                ('mets', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=355, unique=True)),
                ('food_group', models.CharField(blank=True, max_length=255, null=True)),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('serving_description', models.CharField(blank=True, default=1, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('calories_burned', models.FloatField(blank=True, editable=False, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.activitydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('bmr', models.FloatField()),
                ('calories_in', models.FloatField()),
                ('calories_out', models.FloatField()),
                ('net_calories', models.FloatField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('serving_count', models.PositiveIntegerField()),
                ('total_calories', models.FloatField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.fooddata')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.mealtype')),
            ],
        ),
    ]
