# Generated by Django 5.1.3 on 2024-11-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_weighthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighthistory',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
