# Generated by Django 5.1.3 on 2024-12-03 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_weighthistory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
